#!/bin/sh

# XEP Graphical Aide

XEP_HOME="/Users/dclunie/Documents/Work/DICOM_Publish_XML/DocBookDICOM2013/XEP"
JAVA_HOME="/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home"
CP="$XEP_HOME/lib/xep.jar:\
$XEP_HOME/lib/x4u.jar:\
$XEP_HOME/lib/saxon6.5.5/saxon.jar:\
$XEP_HOME/lib/saxon6.5.5/saxon-xml-apis.jar:\
$XEP_HOME/lib/xt.jar:\
$XEP_HOME/lib/crimson.jar"

"$JAVA_HOME/bin/java" \
	"-Dcom.renderx.xep.CONFIG=$XEP_HOME/xep.xml" \
	-cp "$CP" \
	com.renderx.xepx.x4u.as.Assistant "$@"
